"""
Common definitions for the DADCA simulation: constants, agent types,
message schemas, and state machines.
"""
import enum
from typing import TypedDict

# ---------------------------------------------------------------------------
# Constants — tweak these to change simulation behaviour
# ---------------------------------------------------------------------------

BATTERY_CAPACITY      = 100.0    # abstract battery units (not metres)
BATTERY_DRAIN_RATE    = 0.05     # battery units lost per metre flown
BATTERY_LOW_THRESHOLD = 0.25     # go recharge when battery drops below this fraction
RECHARGE_TIME         = 30.0     # seconds to fully recharge
RECHARGE_RATE         = BATTERY_CAPACITY / RECHARGE_TIME   # battery units / second
UAV_SPEED             = 3.0      # m/s

COMM_RANGE            = 20.0     # radio range (m)

SENSOR_PACKET_INTERVAL = 4.0     # seconds between each packet generated by a sensor

# Stagger UAV departures so they never hit the low-battery threshold at the
# same time.  Spacing in seconds between each UAV's departure.
UAV_STAGGER_DELAY     = 15.0     # seconds between each UAV's departure

SIMULATION_DURATION = 1000 # seconds that simulation will last

# ---------------------------------------------------------------------------
# 1. Agent types and message schemas
# ---------------------------------------------------------------------------

class AgentType(enum.Enum):
    SENSOR         = 0
    UAV            = 1
    BASE_STATION   = 2
    ENERGY_STATION = 3


class DADCAMessage(TypedDict):
    packet_count: int
    sender_type:  int
    sender_id:    int


class EStationMessage(TypedDict):
    """
    Protocol between UAVs and the Energy Station.

    msg_type values
    ---------------
    "want_charge"     UAV → broadcast  : I need to charge (announces priority)
    "want_ack"        UAV → UAV        : I acknowledge your want_charge
    "request_charge"  UAV → E-Station  : I am the highest-priority, give me the slot
    "ack_charge"      E-Station → UAV  : slot granted, start charging
    "slot_busy"       E-Station → UAV  : slot taken, retry later
    "charge_done"     UAV → E-Station  : I'm done, releasing the slot
    "slot_free"       E-Station → all  : slot is free (broadcast)
    """
    msg_type:     str
    sender_id:    int
    battery:      float
    packet_count: int


# ---------------------------------------------------------------------------
# UAV state machine
# ---------------------------------------------------------------------------

class UAVState(enum.Enum):
    PATROLLING  = "patrolling"    # Normal DADCA shuttle
    TO_ESTATION = "to_estation"   # Flying toward E-Station
    ANNOUNCING  = "announcing"    # Broadcasting want_charge, collecting peer replies
    WAITING     = "waiting"       # Not highest priority — waiting for slot_free
    CHARGING    = "charging"      # Actively charging
    RETURNING   = "returning"     # Flying back to resume patrol (transient)